### ISSUE TITLE
Question about some of the shader logic

### ISSUE THREAD

**Issue by zacharycarter** [jdupuy/LongestEdgeBisection2D#1]
Hello @jdupuy !

Thanks for linking me to this repo from your opengl-framework repo. I've successfully ported the terrain example to https://bkaradzic.github.io/bgfx (which also has an example featuring the opengl-framework tessellated terrain example), and gotten things working with the OpenGL backend.

I'm attempting to port the example to d3d11 - however I'm having trouble understanding what some of the glsl code does. Specifically this function:

```
vec4[3] DecodeTriangleVertices(in const cbt_Node node)
{
    vec3 xPos = vec3(0, 0, 1), yPos = vec3(1, 0, 0);
    mat2x3 pos = leb_DecodeNodeAttributeArray_Square(node, mat2x3(xPos, yPos));
    vec4 p1 = vec4(pos[0][0], pos[1][0], 0.0, 1.0);
    vec4 p2 = vec4(pos[0][1], pos[1][1], 0.0, 1.0);
    vec4 p3 = vec4(pos[0][2], pos[1][2], 0.0, 1.0);

#if FLAG_DISPLACE
    p1.z = u_DmapFactor * texture(u_DmapSampler, p1.xy).r;
    p2.z = u_DmapFactor * texture(u_DmapSampler, p2.xy).r;
    p3.z = u_DmapFactor * texture(u_DmapSampler, p3.xy).r;
#endif

    return vec4[3](p1, p2, p3);
}
```

What exactly do`xPos`'s and `yPos`'s values mean? I've transposed all the matrices in `leb.sh` so that they follow the correct convention for d3d11. I tried swapping the indices in this portion of the code - 

```
vec4 p1 = vec4(pos[0][0], pos[1][0], 0.0, 1.0);
vec4 p2 = vec4(pos[0][1], pos[1][1], 0.0, 1.0);
vec4 p3 = vec4(pos[0][2], pos[1][2], 0.0, 1.0);
```

So that I'm accessing the matrix components with a row-major convention - 
```
vec4 p1 = vec4(pos[0][0], pos[0][1], 0.0, 1.0);
vec4 p2 = vec4(pos[1][0], pos[1][1], 0.0, 1.0);
vec4 p3 = vec4(pos[2][0], pos[2][1], 0.0, 1.0);
```

However the vertex positions and UVs still don't look right when compared to those produced by the GLSL shader code.

Any hints you might be able to provide me here, I would greatly appreciate. I tried to grok as much as I could from the white paper but I'm stuck on this portion...

**Comment by jdupuy** [comment]
Hi @zacharycarter,

The `xPos` and `yPos` denote the `x` and `y` coordinates of the base triangle with vertices `(xPos[0], yPos[0]), (xPos[1], yPos[1]), (xPos[2], yPos[2])`.

I've actually ported my GLSL libraries to HLSL so that they run in the Unity Game Engine. I put my ports (libcbt and libleb) in the attached ZIP file. You'll also find the vertex shader I use in Unity, which shows you how to get the vertex positions and texCoords for the terrain. Let me know if this helps :)

PS: I'll also add the files to my original repos so that everybody can use them.

[unity-shaders.zip](https://github.com/jdupuy/LongestEdgeBisection2D/files/5328070/unity-shaders.zip)

**Comment by zacharycarter** [comment]
@jdupuy - thanks so much for the explanation and sharing the Unity shaders! I really appreciate the help!

**Comment by jdupuy** [comment]
You're welcome @zacharycarter ! I also forgot to thank you for porting this work (and the previous one !) in BGFX, which is a great project IMO :)

**Comment by zacharycarter** [comment]
@jdupuy I didn't actually port the previous example - but that did inspire me to port this one :)

Thanks again for sharing the Unity shaders - I realized I was performing matrix multiplication on a per-component basis for d3d, so I've addressed that.

I'm still struggling though to get this fully working with d3d. Here's what I have currently - 

![d3d](https://user-images.githubusercontent.com/1181513/95240303-cfc0a400-07d1-11eb-93d9-c2634c013bac.png)

Compared to:

https://i.imgur.com/bbj0fts.mp4

So far as I can tell, one problem I'm facing is that `leb__SplittingMatrix` function is never being called. I'm trying to get to the root of that issue now, and hopefully it continues to unblock me.

**Comment by jdupuy** [comment]
Yes it appears you still have some work left ^^
At this point I believe I would best be able to help you over a zoom / skype / whatever. If that sounds good to you, then I suggest we try to find a suitable date over mail.

**Comment by zacharycarter** [comment]
> Yes it appears you still have some work left ^^
> At this point I believe I would best be able to help you over a zoom / skype / whatever. If that sounds good to you, then I suggest we try to find a suitable date over mail.

<del>That sounds great to me! My email address is carterza@gmail.com. If you email me a day and time that works for you - I can confirm on my end (I'm pretty flexible as far as my schedule goes) and set up a zoom call for us.</del>

I got it working! It was a quirk with BGFX where the only type of buffer that could be read inside of a vertex shader using the d3d11 backend, is a read only buffer. Thanks for all of your help! I'll post a reply here and tag you in it once I have the example submitted to the BGFX repo.

**Comment by jdupuy** [comment]
Fantastic ! Great work :)
