### ISSUE TITLE
Questions About LEB

### ISSUE THREAD

**Issue by realfan-1s** [jdupuy/LongestEdgeBisection2D#2]
Hello @jdupuy !
I'm reading sorce code about LEB and your paper. But I find winding matrix and square matrix，Both are not mentioned in the paper. What are the functions of the two and how are they derived?

**Comment by jdupuy** [comment]
Hi @realfan-1s !

The winding matrix is to make sure the decoded triangle vertices are given in consistent order (always counter-clockwise). If I don't use it, I would end up with clockwise order for even levels, and counter-clockwise for odd levels. This is why I use it at the end of the decoding [here](https://github.com/jdupuy/libleb/blob/da3a01844088ec24461fedd8889ad6449712af5d/leb.h#L487)

The square matrix is to build a square domain on which LEB is applied. I use it [here](https://github.com/jdupuy/libleb/blob/da3a01844088ec24461fedd8889ad6449712af5d/leb.h#L481) 

If you have further questions, feel free to write anytime.
