### ISSUE TITLE
Some questions about cbt_SumReduction

### ISSUE THREAD

**Issue by realfan-1s** [jdupuy/LongestEdgeBisection2D#3]
Hello, I would like to ask what is the role of sumReduction Prepass, and what do the 2-bits and 3-bits etc. written in the comments represent.

**Comment by jdupuy** [comment]
Hi,
The deepest nodes of the CBT are stored using 1-bit, we can thus process 64-nodes at the same time with a 64-bit integer and some bitwise operators. The sum reduction prepass does just that. For more information on the memory layout of the CBT, have a look at Section 3.3 from my paper "Concurrent Binary Trees (with application to longest edge bisection)", link here: https://onrendering.com/data/papers/cbt/ConcurrentBinaryTrees.pdf

**Comment by realfan-1s** [comment]
Hello, which document is the LOD algorithm in the terrain project from?

**Comment by jdupuy** [comment]
> Hello, which document is the LOD algorithm in the terrain project from?

That's unrelated to the SumReduction. Could you please create another issue to keep the discussions focused ? Thanks !
